### ISSUE TITLE
video is being cut off at the end by a few seconds.

### ISSUE THREAD

**Issue by nohandtail** [meew0/Lethe#16]
is there a way to resolve this?

**Comment by nohandtail** [comment]
okay nvm
`currentStream.on('end', () => setTimeout(playStopped, /*extended the value here*/));`

**Comment by meew0** [comment]
Yeah that's the problem, discord.js doesn't end the stream at the correct time so to avoid cutoffs I hard-coded a value in there that works most of the time. In 66fbedf62f983a8fe08e533e2726dc58e13defe0 I changed it so that it loads the value from a config file, so please update Lethe and change the value in lethe-config.json instead.
